name: Storm CMS Page
description: Storm CMS Page
recipes:
  - storm_cms_content_type_base
config:
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.page:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - page
